name: acme.sh

on:
  workflow_dispatch:
env:
  ACMESH_VERSION: latest
  NEW_TAG: latest,20240430
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: itodouble
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Pull original image
        run: docker pull neilpang/acme.sh:${{ env.ACMESH_VERSION }}
      - name: Tag image
        run: |
          IFS=',' read -ra TAGS <<< "${{ env.NEW_TAG }}"
          for tag in "${TAGS[@]}"; do
            docker tag neilpang/acme.sh:${{ env.ACMESH_VERSION }} itodouble/acme.sh:${tag}
          done
      - name: Push image
        run: |
          IFS=',' read -ra TAGS <<< "${{ env.NEW_TAG }}"
          for tag in "${TAGS[@]}"; do
            docker push itodouble/acme.sh:${tag}
          done
