name: frp
on:
  workflow_dispatch:
env:
  FRP_VERSION: 0.61.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to github Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.0.0
      with:
        images: |
          itodouble/frp
          ghcr.io/itodouble/frp
        tags: |
          latest
          ${{ env.FRP_VERSION }}
    - name: Build and push
      uses: docker/build-push-action@v5.1.0
      env:
        NAVIDROME_VERSION: ${{ env.FRP_VERSION }}
      with:
        build-args: FRP_VERSION=${{ env.FRP_VERSION }}
        file: .github/workflows/files/frp/Dockerfile
        push: true
        platforms: |
          linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
