name: halo

on:
  workflow_dispatch:
env:
  HALO_VERSION: 2.13.1
  NEW_TAG: latest,2,2.13,2.13.1,20240306,2-20240306
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: itodouble
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Login to github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull original image
        run: docker pull halohub/halo:${{ env.HALO_VERSION }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: itodouble/halo
          tags: ${{ env.NEW_TAG }}
      - name: Push to GHCR
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            linux/amd64
          registry: ghcr.io
          image: itodouble/halo
          tags: ${{ steps.meta.outputs.tags }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            linux/amd64
          registry: docker.io
          image: itodouble/halo
          tags: ${{ steps.meta.outputs.tags }}
