name: halo

on:
  workflow_dispatch:
env:
  HALO_VERSION: 2.20.5
  NEW_TAG: latest,2,2.20,2.20.5
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: itodouble
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Pull original image
        run: docker pull halohub/halo:${{ env.HALO_VERSION }}
      - name: Tag image
        run: |
          IFS=',' read -ra TAGS <<< "${{ env.NEW_TAG }}"
          for tag in "${TAGS[@]}"; do
            docker tag halohub/halo:${{ env.HALO_VERSION }} itodouble/halo:${tag}
          done
      - name: Push image
        run: |
          IFS=',' read -ra TAGS <<< "${{ env.NEW_TAG }}"
          for tag in "${TAGS[@]}"; do
            docker push itodouble/halo:${tag}
          done
