name: homarr

on:
  workflow_dispatch:
env:
  HOMARR_VERSION: 0.15.6
  NEW_TAG: latest,0.15.6
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: itodouble
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Pull original image
        run: docker pull ghcr.io/ajnart/homarr:${{ env.HOMARR_VERSION }}

      - name: Tag image
        run: |
          IFS=',' read -ra TAGS <<< "${{ env.NEW_TAG }}"
          for tag in "${TAGS[@]}"; do
            docker tag ghcr.io/ajnart/homarr:${{ env.HOMARR_VERSION }} itodouble/homarr:${tag}
          done
      - name: Push image
        run: |
          IFS=',' read -ra TAGS <<< "${NEW_TAG}"
          for tag in "${TAGS[@]}"; do
            docker push itodouble/homarr:${tag}
          done
