name: music-tag-web-v2

on:
  workflow_dispatch:
env:
  MUSIC_TAG_VERSION: 2.0.7
  NEW_TAG: latest,2,2.0.7,2.0.7-20240422,2-2024042
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: itodouble
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Pull original image
        run: docker pull xhongc/music_tag_web:${{ env.MUSIC_TAG_VERSION }}

      - name: Tag image
        run: |
          IFS=',' read -ra TAGS <<< "${{ env.NEW_TAG }}"
          for tag in "${TAGS[@]}"; do
            docker tag xhongc/music_tag_web:${{ env.MUSIC_TAG_VERSION }} itodouble/music-tag-web:${tag}
          done
      - name: Push image
        run: |
          IFS=',' read -ra TAGS <<< "${NEW_TAG}"
          for tag in "${TAGS[@]}"; do
            docker push itodouble/music-tag-web:${tag}
          done
